package proyecto_logica2;

import fonts.CustomFont;

public class Main extends javax.swing.JFrame {

    CustomFont fontType;
    
    public Main() {
        initComponents();
        fontType = new CustomFont();
        jLTitle.setFont(fontType.loadFont(fontType.encodeSans, 1, 40));
        jBtnAdopt.setFont(fontType.loadFont(fontType.encodeSans, 1, 16));
        jBtnManage.setFont(fontType.loadFont(fontType.encodeSans, 1, 16));
        jBtnInfo.setFont(fontType.loadFont(fontType.encodeSans, 1, 16));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jPanelContent = new javax.swing.JPanel();
        jBtnAdopt = new custom_components.JRoundButton();
        jBtnInfo = new custom_components.JRoundButton();
        jBtnManage = new custom_components.JRoundButton();
        petImage = new javax.swing.JLabel();
        jPanelMain = new custom_components.JPanelGradient();
        jLTitle = new javax.swing.JLabel();
        Circle2 = new javax.swing.JLabel();
        Circle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setForeground(new java.awt.Color(0, 0, 0));

        jBtnAdopt.setBackground(new java.awt.Color(50, 205, 76));
        jBtnAdopt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnAdopt.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdopt.setText("Adoptar");
        jBtnAdopt.setBorderPainted(false);
        jBtnAdopt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAdopt.setDefaultCapable(false);
        jBtnAdopt.setFocusPainted(false);
        jBtnAdopt.setFocusable(false);
        jBtnAdopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdoptActionPerformed(evt);
            }
        });

        jBtnInfo.setBackground(new java.awt.Color(50, 205, 76));
        jBtnInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnInfo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnInfo.setText("Info");
        jBtnInfo.setBorderPainted(false);
        jBtnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInfoActionPerformed(evt);
            }
        });

        jBtnManage.setBackground(new java.awt.Color(50, 205, 76));
        jBtnManage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnManage.setForeground(new java.awt.Color(255, 255, 255));
        jBtnManage.setText("Administración");
        jBtnManage.setBorderPainted(false);
        jBtnManage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnManageActionPerformed(evt);
            }
        });

        petImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        petImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adopted-pet.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnAdopt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnManage, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jBtnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(petImage)
                .addGap(40, 40, 40))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jBtnAdopt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBtnManage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(petImage)
                .addGap(24, 24, 24))
        );

        jLTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitle.setText("MundoPets");

        Circle2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Circle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circle.png"))); // NOI18N
        Circle2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Circle1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Circle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circle.png"))); // NOI18N
        Circle1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(Circle1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Circle2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Circle2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Circle1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelGeneralLayout = new javax.swing.GroupLayout(jPanelGeneral);
        jPanelGeneral.setLayout(jPanelGeneralLayout);
        jPanelGeneralLayout.setHorizontalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneralLayout.createSequentialGroup()
                .addGroup(jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelGeneralLayout.setVerticalGroup(
            jPanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGeneralLayout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jBtnAdoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdoptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnAdoptActionPerformed

    private void jBtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInfoActionPerformed

        //Este boton es para el punto 9 y 10
    }//GEN-LAST:event_jBtnInfoActionPerformed

    private void jBtnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnManageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnManageActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Circle1;
    private javax.swing.JLabel Circle2;
    private javax.swing.JButton jBtnAdopt;
    private javax.swing.JButton jBtnInfo;
    private javax.swing.JButton jBtnManage;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel petImage;
    // End of variables declaration//GEN-END:variables
}
